client_docrm_uuid_field_id: 1295057
broker_url: amqp://blumenkraft:TXpVp3SrVaVaTH27g779Gh2jzr64WUFz@localhost//
client_email_field_id: 1130959
client_full_paid_date_field_id: 1295013
client_has_active_group_deal_field_id: 1295023
client_has_active_group_deal_no_value_id: 792047
client_has_active_group_deal_yes_value_id: 792045
client_has_active_individual_deal_field_id: 1295025
client_has_active_individual_deal_no_value_id: 792051
client_has_active_individual_deal_yes_value_id: 792049
client_has_full_paid_field_id: 1295011
client_has_full_paid_no_value_id: 792043
client_has_full_paid_yes_value_id: 792041
client_has_prepaid_field_id: 1295005
client_has_prepaid_no_value_id: 792039
client_has_prepaid_yes_value_id: 792037
client_id: 2affbbaf-cf29-49a6-9a37-d7a5d21471e3
client_is_in_group_schedule_field_id: 1295029
client_is_in_group_schedule_no_value_id: 792059
client_is_in_group_schedule_yes_value_id: 792057
client_is_in_individual_schedule_field_id: 1295031
client_is_in_individual_schedule_no_value_id: 792063
client_is_in_individual_schedule_yes_value_id: 792061
client_is_in_schedule_field_id: 1295027
client_is_in_schedule_no_value_id: 792055
client_is_in_schedule_yes_value_id: 792053
client_last_cancelled_record_date_field_id: 1295047
client_last_deal_paid_sum_field_id: 1295015
client_last_group_deal_end_date_field_id: 1295035
client_last_group_lesson_visit_date_field_id: 1295033
client_last_group_lesson_visit_direction_field_id: 1295049
client_last_group_lesson_visit_teacher_field_id: 1295045
client_last_individual_lesson_visit_date_field_id: 1295051
client_last_individual_lesson_visit_teacher_field_id: 1295053
client_last_prepaid_date_field_id: 1295007
client_last_prepaid_sum_field_id: 1295009
client_last_receive_time_field_id: 1295041
client_last_record_date_field_id: 1295039
client_last_visited_trial_lesson_date_field_id: 1295001
client_last_visited_trial_lesson_direction_field_id: 1295003
client_last_visited_trial_lesson_teacher_field_id: 671921
client_paid_group_count_field_id: 1295017
client_paid_individual_count_field_id: 1295019
client_paid_sum_full_field_id: 1295021
client_remained_group_lesson_count_field_id: 1295037
client_remained_individual_lesson_count_field_id: 1295055
client_secret: EBITXN1V3IoZ5gIw2ebMlMbRR5mPGIlEMgd8Mfov6DstEmNoNoS0cG6tTp4fUVS8
client_visited_trial_lesson_field_id: 1294999
client_visited_trial_no_value_id: 792035
client_visited_trial_yes_value_id: 792033
code: def502009b9c50eabe17c31702f2afdc40f78521fa56950a2a922e37dcb573a0e57941c7d21edd7a905ffc84b0875198bae096129b1ec6ebf95d40c1ba2414fad28ff9d7c6bab28f8dbb5c7799721b41de07667093588de32126341984f623c3833899681269bb15f7f2e2c7c791b16da6d8abc3e4b93b0f176667fd3ad2d6e683121fef267cf6a9bf06aee536eb1d8d46a56dade260d80ee4876088a5afc7a699c6c402f6a09fd678765efb39a0551990254829093baf6b601d9f7e9922066343ea5a895d823199389b2daffd1950ce2d8f87e11c7e133aa422658a3e0cb51601a88101d9ffce8c6abe3dc35579dba480ec5ff4dc2ff3534221cd1e9c7815cd3eb3216c781c1c99e2238c310f2a7822602cd7bedba3743ccb742e67371d623e194b898cb9fb63c9ceb1255bac6f85e5735603e9fd6f3ce07a229ba8c6e4987c605b83cde90ae42112e6d4987bfbd67a93113ff97b298d0a4b4488fa1748d0403dcb7b2052af5bdd4213befded0533428e7c5acc6cebaebe243dbbcba90f5bde061514d78e1cb5ffd9273c0dd4f4f2bc1ac49e4f0c1cdaffafb8fe2695d300180543bd3625f33c6bdc1374ac4466f6f80587205cc4d422ae72aa151ef61a550e66fcc8db4421251cf0fe2297836469fcaf730fa0755ac17097c33fe3c27780013e4da5d9bd0439a017e8ec65b65204b19629
count_paid_active_subscriptions_id: 1294949
count_paid_full_paid_subscriptions_id: 1294937
count_paid_partially_paid_subscriptions_id: 1294945
count_paid_promo_active_subscriptions_id: 1294967
count_paid_promo_full_paid_subscriptions_id: 1294965
db_url: postgresql://postgres:Guitardo100@amo.docrm.org:5442/sms_validator
docrm_url: https://new-amo-uat.docrm.org
event_leads_pipeline_id: 6586034
has_free_promo_visited_lesson_id: 1294973
has_free_promo_visited_lesson_no_id: 792031
has_free_promo_visited_lesson_yes_id: 792029
has_paid_active_not_used_subscription_id: 1294951
has_paid_active_not_used_subscription_no_value_id: 792015
has_paid_active_not_used_subscription_yes_value_id: 792013
has_paid_active_subscription_with_remaining_units_id: 1294953
has_paid_active_subscription_with_remaining_units_no_value_id: 792019
has_paid_active_subscription_with_remaining_units_yes_value_id: 792017
has_paid_archive_subscription_with_remaining_units_id: 1294955
has_paid_archive_subscription_with_remaining_units_no_value_id: 792023
has_paid_archive_subscription_with_remaining_units_yes_value_id: 792021
has_paid_promo_visited_lesson_id: 1294957
has_paid_promo_visited_lesson_no_value_id: 792027
has_paid_promo_visited_lesson_yes_value_id: 792025
last_free_promo_visited_lesson_subject_name_id: 1294977
last_free_promo_visited_lesson_teacher_name_id: 1294979
last_free_promo_visited_lesson_visit_date_id: 1294975
last_paid_full_paid_subscription_last_payment_date_id: 1294939
last_paid_full_paid_subscription_last_payment_sum_id: 1294941
last_paid_full_paid_subscription_subject_names_id: 1295059
last_paid_future_lesson_date_id: 1294929
last_paid_lesson_date_id: 1294927
last_paid_partially_paid_subscription_last_payment_date_id: 1294947
last_paid_promo_full_paid_subscription_last_payment_date_id: 1294969
last_paid_promo_full_paid_subscription_subject_names_id: 1295061
last_paid_promo_visited_lesson_subject_name_id: 1294961
last_paid_promo_visited_lesson_teacher_name_id: 1294963
last_paid_promo_visited_lesson_visit_date_id: 1294959
last_paid_visited_lesson_date_id: 1294931
last_paid_visited_subject_name_id: 1294933
last_paid_visited_teacher_name_id: 1294935
lead_id_subscription_lessons_field_id: 671493
lead_id_subscription_paid_promo_field_id: 671495
lead_id_subscription_payments_field_id: 671491
lead_openstat_ad_field_id: 659181
lead_openstat_campaign_field_id: 659179
lead_openstat_service_field_id: 659177
lead_openstat_source_field_id: 659183
lead_primary_loss_reason_in_rejection: 0
lead_primary_loss_reason_not_payed: 0
lead_primary_loss_reason_visit_promo_not_payed: 0
lead_roistat_field_id: 659173
lead_roistat_user_field_id: 659173
lead_status_came_event: 142
lead_status_contacted_value_id: 55970986
lead_status_fullpayed_for_course_value_id: 55971022
lead_status_in_schedule_value_id: 55971030
lead_status_missed_promo_value_id: 55971002
lead_status_need_identified_value_id: 55970990
lead_status_needs_schedule_value_id: 55971026
lead_status_new_lead_value_id: 59821582
lead_status_not_contacted_value_id: 55970982
lead_status_payed_for_promo_value_id: 55970982
lead_status_payed_ticket: 55987522
lead_status_prepayed_for_course_value_id: 55971014
lead_status_primary_payed_for_course_value_id: 142
lead_status_primary_rejection: 143
lead_status_recorded_to_promo_value_id: 55970994
lead_status_secondary_payed_value_id: 142
lead_status_secondary_prepayed_value_id: 55971042
lead_status_secondary_rejection: 143
lead_status_visited_promo_value_id: 55971006
lead_status_zero_lessons_remained_value_id: 55971034
lead_statuses_exclude:
- 142
- 143
lead_utm_campaign_field_id: 659161
lead_utm_content_field_id: 659165
lead_utm_medium_field_id: 659159
lead_utm_referrer_field_id: 659167
lead_utm_source_field_id: 659157
lead_utm_term_field_id: 659163
primary_leads_pipeline_id: 7156898
redirect_url: https://amo.docrm.org/guitardo-ch
secondary_leads_pipeline_id: 6583546
settings_task_type_fullpay_to_current_manager: false
settings_task_type_promo_retro_to_current_manager: false
settings_task_type_reregister_to_current_manager: false
subdomain: amoamodocrmorg
task_queue: new-amo-uat
task_type_cc_processing_site_value_id: 2839402
task_type_cc_promo_register_value_id: 2839406
task_type_cc_promo_reregister_value_id: 2839414
task_type_cc_recall_value_id: 2839426
task_type_confirmation: 2839414
task_type_fill_info_value_id: 2839438
task_type_fullpay_value_id: 2839426
task_type_promo_retro_value_id: 2839418
task_type_register_new_value_id: 2839434
task_type_renew_value_id: 2839430
token_directory: /tokens_guitardo/
use_confirmation_tasks: true
user_admin_1_id: 591924
user_admin_2_id: 591924
user_admin_id: 9609186
user_free_cc_tasks_holder_id: 9609186
user_sales_leader_online_id: 9609186
user_sales_person_id: 9609186
user_technician_id: 9609186
uses_sales_offl: 9609186
utc_delta_seconds: 10800
web_port: 8093
